# Generated by Django 4.2.16 on 2025-10-03 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("id_card", models.CharField(max_length=18, verbose_name="身份证号")),
                ("contact_info", models.CharField(max_length=100, verbose_name="联系方式")),
            ],
            options={
                "verbose_name": "进场人员",
                "verbose_name_plural": "进场人员",
                "db_table": "entry_personnel",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                (
                    "completion_status",
                    models.BooleanField(default=False, verbose_name="完成状态"),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="订单号"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="事件描述"),
                ),
            ],
            options={
                "verbose_name": "事件",
                "verbose_name_plural": "事件",
                "db_table": "event",
            },
        ),
        migrations.CreateModel(
            name="RoomEvent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.room"
                    ),
                ),
            ],
            options={
                "db_table": "room_event",
                "unique_together": {("room", "event")},
            },
        ),
        migrations.CreateModel(
            name="EventEntryPersonnel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "entry_personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.entrypersonnel",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
            options={
                "db_table": "event_entry_personnel",
                "managed": True,
                "unique_together": {("event", "entry_personnel")},
            },
        ),
        migrations.CreateModel(
            name="EventDutyPersonnel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "duty_personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.dutypersonnel",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
            options={
                "db_table": "event_duty_personnel",
                "unique_together": {("event", "duty_personnel")},
            },
        ),
        migrations.CreateModel(
            name="EventDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage_start",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用开始时间"),
                ),
                (
                    "usage_end",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用结束时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待使用"),
                            ("in_use", "使用中"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="使用状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="使用说明")),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.device",
                        verbose_name="关联设备",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="关联事件",
                    ),
                ),
            ],
            options={
                "verbose_name": "事件设备关联",
                "verbose_name_plural": "事件设备关联",
                "db_table": "event_device",
                "unique_together": {("event", "device")},
            },
        ),
        migrations.CreateModel(
            name="EventClient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.client"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
            options={
                "db_table": "event_client",
                "unique_together": {("event", "client")},
            },
        ),
        migrations.CreateModel(
            name="EventAuthorizedOrg",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "authorized_org",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.authorizedorg",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
            options={
                "db_table": "event_authorized_org",
                "unique_together": {("event", "authorized_org")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="authorized_orgs",
            field=models.ManyToManyField(
                related_name="events",
                through="events.EventAuthorizedOrg",
                to="common.authorizedorg",
                verbose_name="授权单位",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="clients",
            field=models.ManyToManyField(
                related_name="events",
                through="events.EventClient",
                to="common.client",
                verbose_name="相关客户",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="devices",
            field=models.ManyToManyField(
                related_name="events",
                through="events.EventDevice",
                to="devices.device",
                verbose_name="关联设备",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="duty_personnel",
            field=models.ManyToManyField(
                related_name="events",
                through="events.EventDutyPersonnel",
                to="common.dutypersonnel",
                verbose_name="值班人员",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="entry_personnel",
            field=models.ManyToManyField(
                related_name="events",
                through="events.EventEntryPersonnel",
                to="events.entrypersonnel",
                verbose_name="进场人员",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="rooms",
            field=models.ManyToManyField(
                related_name="events",
                through="events.RoomEvent",
                to="devices.room",
                verbose_name="相关机房",
            ),
        ),
        migrations.CreateModel(
            name="EventDecommissionedDevice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "decommission_date",
                    models.DateField(auto_now_add=True, verbose_name="下架日期"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "decommissioned_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.decommissioneddevice",
                        verbose_name="关联下架设备",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="关联事件",
                    ),
                ),
            ],
            options={
                "verbose_name": "事件下架设备关联",
                "verbose_name_plural": "事件下架设备关联",
                "db_table": "event_decommissioned_device",
                "unique_together": {("event", "decommissioned_device")},
            },
        ),
    ]
