# Generated by Django 4.2.16 on 2025-12-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0005_warehousedevice_warehousedevicehistory_and_more"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="devices",
            field=models.ManyToManyField(
                related_name="related_events",
                through="events.EventDevice",
                to="devices.device",
                verbose_name="关联设备",
            ),
        ),
        migrations.CreateModel(
            name="EventWarehouseDevice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "warehouse_date",
                    models.DateField(auto_now_add=True, verbose_name="入库日期"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="关联事件",
                    ),
                ),
                (
                    "warehouse_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.warehousedevice",
                        verbose_name="关联仓库设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "事件仓库设备关联",
                "verbose_name_plural": "事件仓库设备关联",
                "db_table": "event_warehouse_device",
                "unique_together": {("event", "warehouse_device")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="warehouse_devices",
            field=models.ManyToManyField(
                related_name="related_events",
                through="events.EventWarehouseDevice",
                to="devices.warehousedevice",
                verbose_name="关联仓库设备",
            ),
        ),
    ]
