# Generated by Django 4.2.16 on 2026-01-31 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0002_alter_event_devices_eventwarehousedevice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationStoryImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(max_length=100, unique=True, verbose_name="批次ID"),
                ),
                (
                    "import_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="导入时间"),
                ),
                ("event_count", models.IntegerField(default=0, verbose_name="创建事件数")),
                ("device_count", models.IntegerField(default=0, verbose_name="处理设备数")),
                (
                    "skipped_events",
                    models.IntegerField(default=0, verbose_name="跳过事件数"),
                ),
                (
                    "skipped_devices",
                    models.IntegerField(default=0, verbose_name="跳过设备数"),
                ),
                (
                    "incremental",
                    models.BooleanField(default=False, verbose_name="增量导入"),
                ),
                (
                    "personnel_sheet",
                    models.CharField(max_length=100, verbose_name="人员进出表Sheet名称"),
                ),
                (
                    "install_sheet",
                    models.CharField(max_length=100, verbose_name="上架汇总表Sheet名称"),
                ),
                (
                    "decommission_sheet",
                    models.CharField(max_length=100, verbose_name="下架汇总表Sheet名称"),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, null=True, verbose_name="导入摘要"),
                ),
                ("event_ids", models.JSONField(default=list, verbose_name="创建的事件ID列表")),
                (
                    "device_sns",
                    models.JSONField(default=list, verbose_name="处理的设备序列号列表"),
                ),
                (
                    "rolled_back",
                    models.BooleanField(default=False, verbose_name="是否已回滚"),
                ),
                (
                    "rolled_back_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="回滚时间"),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="导入用户",
                    ),
                ),
                (
                    "rolled_back_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollback_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="回滚用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "运维故事导入记录",
                "verbose_name_plural": "运维故事导入记录",
                "db_table": "operation_story_import",
                "ordering": ["-import_time"],
                "indexes": [
                    models.Index(
                        fields=["batch_id"], name="operation_s_batch_i_6baa34_idx"
                    ),
                    models.Index(
                        fields=["import_time"], name="operation_s_import__ce62d3_idx"
                    ),
                    models.Index(
                        fields=["imported_by", "import_time"],
                        name="operation_s_importe_118ea1_idx",
                    ),
                    models.Index(
                        fields=["rolled_back"], name="operation_s_rolled__5adabc_idx"
                    ),
                ],
            },
        ),
    ]
