# Generated by Django 4.2.16 on 2026-01-31 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_operationstoryimport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventdevice",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="eventdevice",
            name="status",
        ),
        migrations.RemoveField(
            model_name="eventdevice",
            name="usage_end",
        ),
        migrations.RemoveField(
            model_name="eventdevice",
            name="usage_start",
        ),
    ]
