# Generated by Django 4.2.16 on 2026-01-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_remove_eventdevice_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventdecommissioneddevice",
            name="decommission_date",
        ),
        migrations.RemoveField(
            model_name="eventdecommissioneddevice",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="eventwarehousedevice",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="eventwarehousedevice",
            name="warehouse_date",
        ),
        migrations.AlterField(
            model_name="eventdecommissioneddevice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="eventwarehousedevice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
