# Generated by Django 4.2.16 on 2026-02-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_remove_m2m_extra_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(db_index=True, verbose_name="日期"),
        ),
        migrations.AlterField(
            model_name="event",
            name="order_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, verbose_name="订单号"
            ),
        ),
        migrations.AlterField(
            model_name="eventdecommissioneddevice",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="eventwarehousedevice",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
