# Generated by Django 4.2.16 on 2025-10-03 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cabinet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="机柜名称")),
            ],
            options={
                "verbose_name": "机柜",
                "verbose_name_plural": "机柜",
                "db_table": "cabinet",
            },
        ),
        migrations.CreateModel(
            name="DecommissionedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sn",
                    models.CharField(max_length=100, unique=True, verbose_name="SN"),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="品牌")),
                ("model", models.CharField(max_length=100, verbose_name="型号")),
                ("u_size", models.IntegerField(verbose_name="U数")),
                (
                    "rack_position",
                    models.CharField(max_length=100, verbose_name="机架位置"),
                ),
                ("power", models.CharField(max_length=100, verbose_name="电源")),
                (
                    "decommission_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="下架时间"),
                ),
                ("decommission_reason", models.TextField(verbose_name="下架原因")),
                (
                    "status",
                    models.CharField(
                        choices=[("decommissioned", "已下架"), ("scrapped", "已报废")],
                        default="decommissioned",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "下架设备",
                "verbose_name_plural": "下架设备",
                "db_table": "decommissioned_device",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="品牌")),
                ("model", models.CharField(max_length=100, verbose_name="型号")),
                ("sn", models.CharField(max_length=100, verbose_name="SN")),
                ("u_size", models.IntegerField(verbose_name="U数")),
                (
                    "rack_position",
                    models.CharField(max_length=100, verbose_name="机架位置"),
                ),
                ("power", models.CharField(max_length=100, verbose_name="电源")),
                (
                    "power_wattage",
                    models.IntegerField(
                        blank=True,
                        help_text="设备的电源功率，单位：瓦特(W)",
                        null=True,
                        verbose_name="电源瓦数",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("server", "服务器"),
                            ("switch", "交换机"),
                            ("router", "路由器"),
                            ("firewall", "防火墙"),
                            ("storage", "存储设备"),
                            ("ups", "UPS"),
                            ("pdu", "PDU"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="设备类型",
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="devices.cabinet",
                        verbose_name="所在机柜",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
                "db_table": "device",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="机房名称")),
            ],
            options={
                "verbose_name": "机房",
                "verbose_name_plural": "机房",
                "db_table": "room",
            },
        ),
        migrations.CreateModel(
            name="DeviceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="告警标题")),
                ("description", models.TextField(verbose_name="告警描述")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "提示"),
                            ("warning", "警告"),
                            ("critical", "严重"),
                            ("emergency", "紧急"),
                        ],
                        default="warning",
                        max_length=20,
                        verbose_name="告警级别",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "新增"),
                            ("acknowledged", "已确认"),
                            ("resolved", "已解除"),
                            ("closed", "已关闭"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="告警状态",
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发现时间"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="解决时间"),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, null=True, verbose_name="解决备注"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="devices.device",
                        verbose_name="关联设备",
                    ),
                ),
                (
                    "duty_personnel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.dutypersonnel",
                        verbose_name="值班人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备告警",
                "verbose_name_plural": "设备告警",
                "db_table": "device_alert",
                "ordering": ["-discovered_at"],
            },
        ),
    ]
