# Generated by Django 4.2.16 on 2025-10-03 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="decommissioneddevice",
            name="events",
            field=models.ManyToManyField(
                related_name="decommissioned_devices",
                through="events.EventDecommissionedDevice",
                to="events.event",
                verbose_name="关联事件",
            ),
        ),
        migrations.AddField(
            model_name="cabinet",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cabinets",
                to="devices.room",
                verbose_name="所在机房",
            ),
        ),
    ]
