# Generated by Django 4.2.16 on 2025-12-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("devices", "0004_merge_0002_0003"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="设备名称"
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="品牌")),
                ("model", models.CharField(max_length=100, verbose_name="型号")),
                (
                    "sn",
                    models.CharField(max_length=100, unique=True, verbose_name="序列号"),
                ),
                ("u_size", models.IntegerField(verbose_name="U数")),
                (
                    "power_type",
                    models.CharField(
                        choices=[("single", "单电源"), ("dual", "双电源")],
                        default="single",
                        max_length=20,
                        verbose_name="单/双电源",
                    ),
                ),
                (
                    "power",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="电源规格"
                    ),
                ),
                (
                    "power_wattage",
                    models.IntegerField(
                        blank=True,
                        help_text="设备的电源功率，单位：瓦特(W)",
                        null=True,
                        verbose_name="电源瓦数",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("server", "服务器"),
                            ("switch", "交换机"),
                            ("router", "路由器"),
                            ("firewall", "防火墙"),
                            ("storage", "存储设备"),
                            ("ups", "UPS"),
                            ("pdu", "PDU"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="设备类型",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="供货方"
                    ),
                ),
                (
                    "collection_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="代收时间"),
                ),
                (
                    "warehouse_location",
                    models.CharField(
                        blank=True,
                        help_text="设备在仓库中的存储位置，如：A区-01号货架",
                        max_length=200,
                        null=True,
                        verbose_name="仓库位置",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_warehouse", "在库"),
                            ("installed", "已上架"),
                            ("out_of_warehouse", "已出库"),
                        ],
                        default="in_warehouse",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "仓库设备",
                "verbose_name_plural": "仓库设备",
                "db_table": "warehouse_device",
                "ordering": ["-collection_time"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseDeviceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("in", "入库"),
                            ("install", "上架"),
                            ("out", "出库"),
                            ("update", "更新"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("action_date", models.DateField(verbose_name="操作日期")),
                (
                    "action_time",
                    models.TimeField(blank=True, null=True, verbose_name="操作时间"),
                ),
                (
                    "install_location",
                    models.CharField(
                        blank=True,
                        help_text="上架到的机柜位置，如：F1D-07-10",
                        max_length=200,
                        null=True,
                        verbose_name="上架位置",
                    ),
                ),
                (
                    "install_rack_position",
                    models.CharField(
                        blank=True,
                        help_text="机架U位，如：17-18",
                        max_length=100,
                        null=True,
                        verbose_name="机架位置",
                    ),
                ),
                (
                    "out_reason",
                    models.TextField(blank=True, null=True, verbose_name="出库原因"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="操作人员"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录创建时间"),
                ),
            ],
            options={
                "verbose_name": "仓库设备历史记录",
                "verbose_name_plural": "仓库设备历史记录",
                "db_table": "warehouse_device_history",
                "ordering": ["-action_date", "-action_time", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="warehousedevicehistory",
            name="cabinet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_install_history",
                to="devices.cabinet",
                verbose_name="机柜",
            ),
        ),
        migrations.AddField(
            model_name="warehousedevicehistory",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="关联事件",
            ),
        ),
        migrations.AddField(
            model_name="warehousedevicehistory",
            name="warehouse_device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_records",
                to="devices.warehousedevice",
                verbose_name="仓库设备",
            ),
        ),
    ]
