# Generated by Django 4.2.16 on 2025-12-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0005_warehousedevice_warehousedevicehistory_and_more"),
        ("events", "0002_alter_event_devices_eventwarehousedevice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehousedevice",
            name="events",
            field=models.ManyToManyField(
                related_name="warehouse_device_events",
                through="events.EventWarehouseDevice",
                to="events.event",
                verbose_name="关联事件",
            ),
        ),
        migrations.AddIndex(
            model_name="warehousedevicehistory",
            index=models.Index(
                fields=["warehouse_device", "-action_date"],
                name="warehouse_d_warehou_a0eaf8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="warehousedevicehistory",
            index=models.Index(
                fields=["action", "-action_date"], name="warehouse_d_action_50485a_idx"
            ),
        ),
    ]
