# Generated by Django 4.2.16 on 2025-12-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_devices_eventwarehousedevice_and_more"),
        ("devices", "0006_warehousedevice_events_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehousedevice",
            name="name",
        ),
    ]
