# Generated by Django 4.2.16 on 2025-12-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0007_remove_warehouse_device_name_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehousedevice",
            name="power",
            field=models.CharField(
                blank=True,
                help_text="备用字段，用于后期扩展需求",
                max_length=100,
                null=True,
                verbose_name="备用字段",
            ),
        ),
    ]
