# Generated by Django 4.2.16 on 2025-12-24 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0008_change_power_to_reserved_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="warehousedevice",
            old_name="power",
            new_name="reserved_field_1",
        ),
    ]
