# Generated by Django 4.2.16 on 2025-12-24 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0009_rename_power_to_reserved_field_1"),
    ]

    operations = [
        # 不需要任何操作，因为数据库列名已经是reserved_field_1
        # 只需要移除模型中的db_column='power'即可
    ]
