# Generated by Django 4.2.16 on 2025-12-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_devices_eventwarehousedevice_and_more"),
        ("devices", "0010_fix_reserved_field_1_column"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cabinetpdudata",
            new_name="cabinet_pdu_pdu_por_a1403f_idx",
            old_name="cabinet_pdu_data_pdu_port_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="cabinetpdudata",
            new_name="cabinet_pdu_pdu_por_e6b66d_idx",
            old_name="cabinet_pdu_data_pdu_port_data_type_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="cabinetpdudata",
            new_name="cabinet_pdu_import__f7d62d_idx",
            old_name="cabinet_pdu_data_import_batch_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="cabinetpdudata",
            new_name="cabinet_pdu_timesta_4a1754_idx",
            old_name="cabinet_pdu_data_timestamp_data_type_idx",
        ),
        migrations.RenameIndex(
            model_name="cabinetpdudata",
            new_name="cabinet_pdu_source_090144_idx",
            old_name="cabinet_pdu_data_source_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="pdudevice",
            new_name="pdu_device_room_id_b6ed75_idx",
            old_name="pdu_device_room_id_circuit_idx",
        ),
        migrations.RenameIndex(
            model_name="pdudevice",
            new_name="pdu_device_device__f9099c_idx",
            old_name="pdu_device_device_name_idx",
        ),
        migrations.RenameIndex(
            model_name="pduport",
            new_name="pdu_port_pdu_dev_48d63a_idx",
            old_name="pdu_port_pdu_device_port_idx",
        ),
        migrations.RenameIndex(
            model_name="pduport",
            new_name="pdu_port_port_id_5e9bff_idx",
            old_name="pdu_port_port_identifier_idx",
        ),
        migrations.RenameIndex(
            model_name="pduport",
            new_name="pdu_port_cabinet_48c3f1_idx",
            old_name="pdu_port_cabinet_id_idx",
        ),
        migrations.AddField(
            model_name="device",
            name="events",
            field=models.ManyToManyField(
                related_name="related_devices",
                through="events.EventDevice",
                to="events.event",
                verbose_name="关联事件",
            ),
        ),
        migrations.AlterField(
            model_name="warehousedevice",
            name="reserved_field_1",
            field=models.CharField(
                blank=True,
                help_text="备用字段，用于后期扩展需求",
                max_length=100,
                null=True,
                verbose_name="备用字段1",
            ),
        ),
    ]
