# Generated by Django 4.2.16 on 2025-12-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0011_unify_power_field_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="decommissioneddevice",
            name="power_type",
            field=models.CharField(
                choices=[("single", "单电源"), ("dual", "双电源")],
                default="single",
                max_length=20,
                verbose_name="单/双电源",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="power_type",
            field=models.CharField(
                choices=[("single", "单电源"), ("dual", "双电源")],
                default="single",
                max_length=20,
                verbose_name="单/双电源",
            ),
        ),
        migrations.AlterField(
            model_name="decommissioneddevice",
            name="power",
            field=models.CharField(
                blank=True,
                help_text="保留字段，用于兼容旧数据",
                max_length=100,
                null=True,
                verbose_name="电源",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="power",
            field=models.CharField(
                blank=True,
                help_text="保留字段，用于兼容旧数据",
                max_length=100,
                null=True,
                verbose_name="电源",
            ),
        ),
    ]
