# Generated by Django 4.2.16 on 2025-12-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0012_add_power_type_to_device_models"),
    ]

    operations = [
        migrations.RenameField(
            model_name="decommissioneddevice",
            old_name="power",
            new_name="reserved_field_1",
        ),
        migrations.AlterField(
            model_name="decommissioneddevice",
            name="reserved_field_1",
            field=models.CharField(
                blank=True,
                db_column="power",
                help_text="备用字段，用于后期扩展需求",
                max_length=100,
                null=True,
                verbose_name="备用字段1",
            ),
        ),
    ]
