# Generated by Django 4.2.16 on 2025-12-24 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0013_rename_power_to_reserved_field_1_in_decommissioned_device"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="power",
        ),
    ]
