# Generated by Django 4.2.16 on 2025-12-24 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0014_remove_power_field_from_device"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decommissioneddevice",
            name="reserved_field_1",
        ),
    ]
