# Generated by Django 4.2.16 on 2025-12-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0015_remove_power_field_from_decommissioned_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="decommissioneddevice",
            name="cabinet",
            field=models.ForeignKey(
                blank=True,
                help_text="记录设备下架前的机柜位置",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decommissioned_devices",
                to="devices.cabinet",
                verbose_name="下架前所在机柜",
            ),
        ),
    ]
