# Generated by Django 4.2.16 on 2025-12-24 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0016_decommissioneddevice_cabinet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehousedevicehistory",
            name="out_reason",
        ),
    ]
