# Generated by Django 4.2.16 on 2026-02-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_add_notification_types"),
        ("devices", "0017_remove_out_reason_from_warehouse_device_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="cabinet",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cabinets",
                to="common.client",
                verbose_name="所属客户",
            ),
        ),
    ]
