# Generated by Django 4.2.16 on 2026-02-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0018_cabinet_add_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decommissioneddevice",
            name="decommission_time",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="下架时间"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="sn",
            field=models.CharField(db_index=True, max_length=100, verbose_name="SN"),
        ),
    ]
