# Generated by Django 4.2.16 on 2025-10-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthorizedOrg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="单位名称")),
                ("contact_info", models.CharField(max_length=100, verbose_name="联系方式")),
            ],
            options={
                "verbose_name": "授权单位",
                "verbose_name_plural": "授权单位",
                "db_table": "authorized_org",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="客户名称")),
                ("contact_info", models.CharField(max_length=100, verbose_name="联系方式")),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "db_table": "client",
            },
        ),
        migrations.CreateModel(
            name="DutyPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("contact_info", models.CharField(max_length=100, verbose_name="联系方式")),
                ("position", models.CharField(max_length=50, verbose_name="职位")),
            ],
            options={
                "verbose_name": "值班人员",
                "verbose_name_plural": "值班人员",
                "db_table": "duty_personnel",
            },
        ),
    ]
