# Generated by Django 4.2.16 on 2025-12-15 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_add_duty_personnel_user_and_history"),
    ]

    operations = []
