# Generated by Django 4.2.16 on 2026-02-16 12:47

from django.db import migrations, models


def drop_columns_if_exists(apps, schema_editor):
    """仅当列存在时删除，避免 DB 与迁移历史不一致时报错"""
    with schema_editor.connection.cursor() as cursor:
        for table, column in [
            ("authorized_org", "contact_info"),
            ("client", "contact_info"),
            ("duty_personnel", "contact_info"),
            ("duty_personnel", "position"),
        ]:
            cursor.execute(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_name = %s AND column_name = %s
                """,
                [table, column],
            )
            if cursor.fetchone():
                cursor.execute(
                    'ALTER TABLE "{}" DROP COLUMN IF EXISTS "{}"'.format(table, column)
                )


def add_columns_if_not_exists(apps, schema_editor):
    """仅当列不存在时添加，避免 DB 已存在列时报错"""
    with schema_editor.connection.cursor() as cursor:
        adds = [
            ("client", "authorized_person", "varchar(100) NOT NULL DEFAULT ''"),
            ("duty_personnel", "employee_id", "varchar(50) NOT NULL DEFAULT ''"),
            ("duty_personnel", "id_card", "varchar(18) NOT NULL DEFAULT ''"),
            ("duty_personnel", "phone", "varchar(20) NOT NULL DEFAULT ''"),
            ("duty_personnel", "type", "varchar(50) NOT NULL DEFAULT ''"),
        ]
        for table, column, col_def in adds:
            cursor.execute(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_name = %s AND column_name = %s
                """,
                [table, column],
            )
            if not cursor.fetchone():
                cursor.execute(
                    'ALTER TABLE "{}" ADD COLUMN "{}" {}'.format(table, column, col_def)
                )


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_add_notification_types"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="modelhistory",
            new_name="model_histo_content_c2d18d_idx",
            old_name="model_hist_content_idx",
        ),
        migrations.RenameIndex(
            model_name="modelhistory",
            new_name="model_histo_changed_920ec4_idx",
            old_name="model_hist_changed_idx",
        ),
        migrations.RenameIndex(
            model_name="modelhistory",
            new_name="model_histo_duty_pe_9ae573_idx",
            old_name="model_hist_duty_idx",
        ),
        migrations.RenameIndex(
            model_name="modelhistory",
            new_name="model_histo_is_admi_962769_idx",
            old_name="model_hist_admin_idx",
        ),
        migrations.RenameIndex(
            model_name="modelhistory",
            new_name="model_histo_reverte_869be6_idx",
            old_name="model_hist_revert_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_201701_idx",
            old_name="notificatio_recipie_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_notific_d281eb_idx",
            old_name="notificatio_notific_idx",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="authorizedorg",
                    name="contact_info",
                ),
                migrations.RemoveField(
                    model_name="client",
                    name="contact_info",
                ),
                migrations.RemoveField(
                    model_name="dutypersonnel",
                    name="contact_info",
                ),
                migrations.RemoveField(
                    model_name="dutypersonnel",
                    name="position",
                ),
            ],
            database_operations=[
                migrations.RunPython(drop_columns_if_exists, migrations.RunPython.noop),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="client",
                    name="authorized_person",
                    field=models.CharField(
                        blank=True, default="", max_length=100, verbose_name="授权人"
                    ),
                ),
                migrations.AddField(
                    model_name="dutypersonnel",
                    name="employee_id",
                    field=models.CharField(
                        blank=True, default="", max_length=50, verbose_name="员工ID"
                    ),
                ),
                migrations.AddField(
                    model_name="dutypersonnel",
                    name="id_card",
                    field=models.CharField(
                        blank=True, default="", max_length=18, verbose_name="身份证号"
                    ),
                ),
                migrations.AddField(
                    model_name="dutypersonnel",
                    name="phone",
                    field=models.CharField(
                        blank=True, default="", max_length=20, verbose_name="电话"
                    ),
                ),
                migrations.AddField(
                    model_name="dutypersonnel",
                    name="type",
                    field=models.CharField(
                        blank=True, default="", max_length=50, verbose_name="类型"
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_columns_if_not_exists, migrations.RunPython.noop),
            ],
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("account_approved", "账户审核通过"),
                    ("account_rejected", "账户审核拒绝"),
                    ("account_pending", "账户待审核"),
                    ("new_event", "新增事件"),
                    ("event_updated", "事件更新"),
                    ("new_alert", "新增告警"),
                    ("system", "系统通知"),
                ],
                max_length=50,
                verbose_name="消息类型",
            ),
        ),
    ]
